#You can copy this code straight into a blank *.yml file. Make sure you create a new *.yml file under the following directory:

#YOUR_GITHUB_USERNAME --> .github --> workflows --> FILE_NAME.yml

# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Step 3. Running GitHub Actions
Once you've added the code above and committed it, head to your Actions tab. Under "Workflows", you should see the "Generate Snake" Action you created above.

Workflow

Click "Run Workflow" and watch your workflow run. You can even expand your workflow and see what's happening in real time.

GIFRunning Actions

Once your workflow has finished running, you should have received a green ✅ "build" checkmark. If so, this means your Action is working nicely. If not, you'll have to go through the code and see where the errors are. The "build" status should give you some indication of where your errors lie. You can also compare it with the yaml file on my GitHub Profile README.

Build green

If you have the green "build" ✅ then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.

GIFCodeOutput

Step 4. Adding a contribution-eating snake to your profile
Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!

GIFSnakeEating
Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?

Git Good (9 Part Series)
1
Using the GitHub CLI to update your repo
2
How to create and pin a gist on GitHub
...
5 more parts...
8
How to use GitHub Pages to host your website, even with multiple repos
9
How to create a Profile README for your Organisation
Top comments (25)

Subscribe
pic
Add to the discussion
 
 
kushaltanna24 profile image
KushalTanna24
•
Jun 3

Work fine.! Here is mine - KushalTanna24


2
 likes
Like
Reply
 
 
msoftware profile image
Michael jentsch
•
Jul 9 '21

Great tutorial! Works for me.
Here's mine - github.com/msoftware


2
 likes
Like
Reply
 
 
gustavohgmartins profile image
Gustavo Martins
•
Sep 2 '21

Awsome! How did you change the background-color?


Like
Reply
 
 
mishmanners profile image
Michelle Mannering 
•
Sep 2 '21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.


1
 like
Like
Thread
 
gustavohgmartins profile image
Gustavo Martins
•
Sep 2 '21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voilá


2
 likes
Like
Thread
 
mishmanners profile image
Michelle Mannering 
•
Sep 2 '21

Awesome! Glad to be of help 😄


1
 like
Like
Reply
 
 
bpolaswar profile image
Bhumesh Polaswar
•
Oct 17 '21

Great worked for me. See github.com/bpolaswar
Thanks.


2
 likes
Like
Reply
 
 
zieldecastro profile image
Josiel de Castro Goudinho
•
Sep 14 '21 • Edited on Sep 14

It does not work for me. Can someone help me?
github.com/zieldecastro
instagram.com/zieldecastro/


1
 like
Like
Reply
 
 
viveeeeeek profile image
VivekS.
•
Oct 2 '21

Awesome!


1
 like
Like
Reply
 
 
shasank27 profile image
Shasank Periwal
•
Aug 7 '21 • Edited on Aug 7

Great tutorial!
But can anyone help me, its not showing all my contributions
github.com/shasank27/shasank27


1
 like
Like
Reply
 
 
mishmanners profile image
Michelle Mannering 
•
Sep 5 '21 • Edited on Sep 5

Hey Shasank. I can't see it on your profile, but to show all contributions, you need to make sure all contributions are turned on your profile. You can do this in your settings:

github.com/YOUR_PROFILE --> Settings --> Profile

Then scroll down to "Contributions" and check the box that says "Include private contributions on my profile".

Hope that helps.


1
 like
Like
Reply
 
 
nirav97120 profile image
Nirav Prajapati
•
Dec 16

Awesome My github profile


1
 like
Like
Reply
 
 
wkylin profile image
wkylin.w
•
May 1

Here's mine:
github.com/wkylin


1
 like
Like
Reply
 
 
laurasiiia profile image
Laura
•
Jan 2 • Edited on Jan 2

Hi, i did everything right and even got the "build" status. But no output branch was created... why is that? Can someone help me? github.com/laurasiiia


1
 like
Like
Reply
 
 
mishmanners profile image
Michelle Mannering 
•
Jan 3

I assume you're working off this folder: github.com/laurasiiia/laurasiiia/b...

Since you've got a newer repo (mine account was set up a number of years ago), you have the default branch set to "main". You might need to change the code to be "main" instead of "master".

I created a PR for you: github.com/laurasiiia/laurasiiia/p...
(run it and see if that works)... it might not but worth a shot. Feel free to jump in other people 😄


1
 like
Like
Reply
 
 
phuocantd profile image
An Nguyễn Phước
•
May 31

How to auto build workflow everyday


1
 like
Like
Reply
 
 
adityamangal1 profile image
Aditya Mangal
•
Jul 22 '21

Awesome Tutorial! 🐍


1
 like
Like
Reply
 
 
wisnuaero profile image
Adida Wisnu Akbara
•
Dec 7

here's mine - github.com/wisnuaero


1
 like
Like
Reply
 
 
brayheart profile image
Tyler Bray
•
Nov 9

Thanks for making this guide!


1
 like
Like
Reply
 
 
matheusroichman profile image
Matheus Roichman
•
Nov 2

Mine is not showing all the contributions :(
github.com/MatheusRoichman/Matheus...


1
 like
Like
Reply
 
 
smartmayukh profile image
Mayukhmali Das
•
Jun 30

Works great !!!!!!!! Here's mine

github.com/Smartmayukh


1
 like
Like
Reply
View full discussion (25 comments)
Code of Conduct • Report abuse
🌚 Friends don't let friends browse without dark mode.
Sorry, it's true.

Read next
daviducolo profile image
Metaprogramming with Ruby
Davide Santangelo - Dec 19

dogukaneren profile image
Rsyslog Servisi ile Uzak Sunucuya log Yazdırma
Doğukan Eren - Dec 9

cicirello profile image
How to Write to Workflow Job Summary from a GitHub Action
Vincent A. Cicirello - Dec 21

094459 profile image
AWS open source newsletter, #139
Ricardo Sueiras - Dec 18


Michelle Mannering
Follow
Developer Advocate | Hackathon Queen | International Speaker
LOCATION
Australia
EDUCATION
The University of Melbourne
WORK
Developer Advocate at GitHub
JOINED
May 28, 2020
More from Michelle Mannering
Why 'release' a project? How to automate releases
#opensource #productivity #github #tooling
How to get ready for Hacktoberfest 2022
#hacktoberfest #opensource #tutorial
GitHub's non-code features
#github #beginners #productivity #opensource

# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: carolinehaoud
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
